In [34]:
#https://www.youtube.com/watch?v=VCJdg7YBbAQ
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [63]:
data = pd.read_csv("G:\\Data CSV\\bankingdata.csv")
# data
data.head()
data.tail()

age         job  marital            education  default housing loan  \
41183   59     retired  married          high.school  unknown      no  yes   
41184   31   housemaid  married             basic.4y  unknown      no   no   
41185   42      admin.   single    university.degree  unknown     yes  yes   
41186   48  technician  married  professional.course       no      no  yes   
41187   25     student   single          high.school       no      no   no   

         contact month day_of_week ...  campaign  pdays  previous  \
41183  telephone   jun         thu ...         1    999         0   
41184  telephone   may         thu ...         2    999         0   
41185  telephone   may         wed ...         3    999         0   
41186  telephone   oct         tue ...         2    999         0   
41187  telephone   may         fri ...         4    999         0   

          poutcome emp_var_rate  cons_price_idx  cons_conf_idx  euribor3m  \
41183  nonexistent          1.4          94.465          -41.8      4.866   
41184  nonexistent          1.1          93.994          -36.4      4.860   
41185  nonexistent          1.1          93.994          -36.4      4.857   
41186  nonexistent         -3.4          92.431          -26.9      0.742   
41187  nonexistent          1.1          93.994          -36.4      4.859   

       nr_employed  y  
41183       5228.1  0  
41184       5191.0  0  
41185       5191.0  0  
41186       5017.5  0  
41187       5191.0  0  

[5 rows x 21 columns]

In [36]:
data.describe()

age      duration      campaign         pdays      previous  \
count  41188.00000  41188.000000  41188.000000  41188.000000  41188.000000   
mean      40.02406    258.285010      2.567593    962.475454      0.172963   
std       10.42125    259.279249      2.770014    186.910907      0.494901   
min       17.00000      0.000000      1.000000      0.000000      0.000000   
25%       32.00000    102.000000      1.000000    999.000000      0.000000   
50%       38.00000    180.000000      2.000000    999.000000      0.000000   
75%       47.00000    319.000000      3.000000    999.000000      0.000000   
max       98.00000   4918.000000     56.000000    999.000000      7.000000   

       emp_var_rate  cons_price_idx  cons_conf_idx     euribor3m  \
count  41188.000000    41188.000000   41188.000000  41188.000000   
mean       0.081886       93.575664     -40.502600      3.621291   
std        1.570960        0.578840       4.628198      1.734447   
min       -3.400000       92.201000     -50.800000      0.634000   
25%       -1.800000       93.075000     -42.700000      1.344000   
50%        1.100000       93.749000     -41.800000      4.857000   
75%        1.400000       93.994000     -36.400000      4.961000   
max        1.400000       94.767000     -26.900000      5.045000   

        nr_employed             y  
count  41188.000000  41188.000000  
mean    5167.035911      0.112654  
std       72.251528      0.316173  
min     4963.600000      0.000000  
25%     5099.100000      0.000000  
50%     5191.000000      0.000000  
75%     5228.100000      0.000000  
max     5228.100000      1.000000

In [68]:
 data.shape
# data.columns
# data=data.dropna()
# data.columns

(41188, 21)

In [60]:
#Data preprocessing:: Create dummy variables, that is variables with only two values, zero and one.
#data2 =pd.get_dummies(data["marital"])
data2=pd.get_dummies(data)
data2

age  duration  campaign  pdays  previous  emp_var_rate  cons_price_idx  \
0       44       210         1    999         0           1.4          93.444   
1       53       138         1    999         0          -0.1          93.200   
2       28       339         3      6         2          -1.7          94.055   
3       39       185         2    999         0          -1.8          93.075   
4       55       137         1      3         1          -2.9          92.201   
5       30        68         8    999         0           1.4          93.918   
6       37       204         1    999         0          -1.8          92.893   
7       39       191         1    999         0          -1.8          92.893   
8       36       174         1      3         1          -2.9          92.963   
9       27       191         2    999         1          -1.8          93.075   
10      34        62         2    999         0           1.1          93.994   
11      41       789         1    999         0           1.4          93.444   
12      55       372         3    999         0           1.4          93.444   
13      33        75         5    999         0          -1.8          92.893   
14      26      1021         1    999         0           1.4          94.465   
15      52       117         2    999         0           1.4          93.918   
16      35      1034         2    999         0          -1.8          93.075   
17      27       540         1    999         0          -0.1          93.798   
18      28       140         1    999         0           1.1          93.994   
19      26       104         4    999         0           1.4          93.918   
20      41       246         1    999         1          -1.8          93.075   
21      35      1114         1    999         0           1.4          94.465   
22      40       340         1    999         0           1.4          93.918   
23      32        35         1    999         0           1.4          93.918   
24      41       241         3    999         0           1.4          93.918   
25      34       168         2    999         0          -1.8          92.893   
26      49        81         1    999         0          -3.4          92.431   
27      37       226         1      2         1          -1.8          93.075   
28      35       746         2    999         0          -1.8          92.893   
29      38        41         5    999         0           1.4          93.918   
...    ...       ...       ...    ...       ...           ...             ...   
41158   30       127         1    999         0           1.4          94.465   
41159   47       129         4    999         0           1.4          93.918   
41160   57       114         2    999         0          -0.1          93.200   
41161   43       339         1    999         0           1.4          93.918   
41162   43       902         2    999         0          -1.8          93.075   
41163   22       396         1    999         0           1.1          93.994   
41164   33       436         2    999         0           1.4          93.444   
41165   56       476         2    999         0           1.4          93.444   
41166   31       208         1    999         0          -1.8          92.893   
41167   30       251         3    999         0           1.4          93.918   
41168   29       254         1    999         0           1.4          93.918   
41169   46       530         1    999         0          -0.1          93.200   
41170   32       195         3    999         0           1.4          93.444   
41171   42       956         2    999         0           1.4          94.465   
41172   27      1309         4    999         0           1.4          93.918   
41173   39       291         1    999         0           1.1          93.994   
41174   49       140         2    999         0          -1.8          92.893   
41175   46        58         3    999 

In [70]:

#data.marital.unique()

(41188, 21)

In [66]:
#Drop the unknown columns
data2.drop(data2.columns[[12,16,18,21,24]],axis=1,inplace=True)
data2.columns


Index(['age', 'duration', 'campaign', 'pdays', 'previous', 'emp_var_rate',
       'cons_price_idx', 'cons_conf_idx', 'euribor3m', 'nr_employed', 'y',
       'job_admin.', 'job_housemaid', 'job_management', 'job_self-employed',
       'job_technician', 'marital_divorced', 'marital_single',
       'education_basic.4y', 'education_basic.6y', 'education_high.school',
       'education_illiterate', 'education_professional.course',
       'education_university.degree', 'education_unknown', 'default_no',
       'default_unknown', 'default_yes', 'housing_no', 'housing_unknown',
       'housing_yes', 'loan_no', 'loan_unknown', 'loan_yes',
       'contact_cellular', 'contact_telephone', 'month_apr', 'month_aug',
       'month_dec', 'month_jul', 'month_jun', 'month_mar', 'month_may',
       'month_nov', 'month_oct', 'month_sep', 'day_of_week_fri',
       'day_of_week_mon', 'day_of_week_thu', 'day_of_week_tue',
       'day_of_week_wed', 'poutcome_failure', 'poutcome_nonexistent',
       'poutcome_

In [67]:
data2.shape

(41188, 54)

In [74]:
# x=data2.iloc[:,1:]
# x
# y=data2.iloc[:,0]
# y

In [93]:
#Split the data into training and test sets
from sklearn.cross_validation import train_test_split
train_x,test_x,train_y,test_y = train_test_split(x,y)


In [97]:
#train_x.shape
#train_y.shape
#test_x.shape
test_y.shape

(10297,)

In [125]:
#logistic regression model.
 
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
classifier =LogisticRegression()
classifier.fit(train_x,train_y)
y_pred = classifier. predict (test_x) 

In [ ]:
from sklearn.metrics import classification_report
classification_report(y_test,y_pred )

In [128]:
#confusion_matrix() function will calculate a confusion matrix and return the result as an array

from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_y, y_pred)
print(confusion_matrix)

[[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 1 2 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [122]:
from sklearn.metrics import accuracy_score
print(accuracy_score(test_y, y_pred))

0.06827231232397786
